# Generated by Django 5.2.6 on 2025-11-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user', models.CharField(default='unknown', max_length=50)),
                ('request_path', models.CharField(max_length=255)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, choices=[('get', 'Get'), ('post', 'Post'), ('put', 'Put'), ('patch', 'Patch'), ('delete', 'Delete')], max_length=20, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_time', models.FloatField(default=0.0, help_text='Total request to response duration in milliseconds (ms)')),
                ('status_code', models.IntegerField(default=200)),
                ('system_logs', models.JSONField(blank=True, help_text='Captured system logs [INFO, DEBUG, ERROR, WARNING].', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('db_query_count', models.IntegerField(default=0, help_text='Total database connection queries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
