# Generated by Django 5.2.6 on 2025-11-23 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footprint',
            options={'verbose_name': 'Footprint', 'verbose_name_plural': 'Footprints'},
        ),
        migrations.AddField(
            model_name='footprint',
            name='request_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the request/response cycle.', max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='request_body',
            field=models.JSONField(blank=True, help_text='Parsed request body (e.g., POST/JSON data).', null=True),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='request_user',
            field=models.CharField(default='anonymous', help_text="Authenticated user ID or 'anonymous'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='system_logs',
            field=models.JSONField(blank=True, help_text='Captured system logs (list of strings).', null=True),
        ),
    ]
