# Generated by Django 6.0 on 2026-01-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider', '0002_alter_footprint_options_footprint_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateField(auto_now_add=True)),
                ('last_seen', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='footprint',
            name='exception_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footprint',
            name='stack_trace',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footprint',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insider.issue'),
        ),
    ]
