# Generated by Django 6.0 on 2026-01-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider', '0003_issue_footprint_exception_name_footprint_stack_trace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_notified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
