# Generated by Django 6.0.1 on 2026-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insider', '0003_alter_insidersetting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
