# Generated by Django 6.0.1 on 2026-02-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insider', '0005_refresh_integrations'),
    ]

    operations = [
    ]
