# Generated by Django 6.0.1 on 2026-02-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insider', '0006_refresh_integrations'),
    ]

    operations = [
    ]
